#!/usr/bin/env bash
# make nginx listen on 80 and status is not running
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
